worker_processes auto;

events {
    worker_connections 16384;
    multi_accept on;
}

http {
    upstream order-app {
        server order-service:5000;
        keepalive 64;
    }
    upstream payment-app {
        server payment-service:5000;
        keepalive 64;
    }
    upstream stock-app {
        server stock-service:5000;
        keepalive 64;
    }
    server {
        listen 80;

        proxy_connect_timeout 2s;
        proxy_read_timeout 30s;
        proxy_send_timeout 5s;
        proxy_next_upstream error timeout http_502 http_503;
        proxy_next_upstream_timeout 5s;
        proxy_next_upstream_tries 2;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        location /orders/ {
           proxy_pass   http://order-app/;
        }
        location /payment/ {
           proxy_pass   http://payment-app/;
        }
        location /stock/ {
           proxy_pass   http://stock-app/;
        }
        access_log off;
    }
    access_log off;
}
