events { worker_connections 2048;}

http {
    upstream order-app {
        server order-service:5000;
    }
    upstream payment-app {
        server payment-service:5000;
    }
    upstream stock-app {
        server stock-service:5000;
    }
    server {
        listen 80;

        proxy_connect_timeout 2s;
        proxy_read_timeout 30s;
        proxy_send_timeout 5s;
        proxy_next_upstream error timeout http_502 http_503;
        proxy_next_upstream_timeout 5s;
        proxy_next_upstream_tries 2;

        location /orders/ {
           proxy_pass   http://order-app/;
        }
        location /payment/ {
           proxy_pass   http://payment-app/;
        }
        location /stock/ {
           proxy_pass   http://stock-app/;
        }
        access_log  /var/log/nginx/server.access.log;
    }
    access_log  /var/log/nginx/access.log;
}
