events { worker_connections 2048;}

http {
    resolver 127.0.0.11 valid=5s ipv6=off;
    server {
        listen 80;
        location /orders/ {
           set $order_backend order-service:5000;
           rewrite ^/orders/(.*)$ /$1 break;
           proxy_http_version 1.1;
           proxy_set_header Connection "";
           proxy_pass   http://$order_backend;
        }
        location /payment/ {
           set $payment_backend payment-service:5000;
           rewrite ^/payment/(.*)$ /$1 break;
           proxy_http_version 1.1;
           proxy_set_header Connection "";
           proxy_pass   http://$payment_backend;
        }
        location /stock/ {
           set $stock_backend stock-service:5000;
           rewrite ^/stock/(.*)$ /$1 break;
           proxy_http_version 1.1;
           proxy_set_header Connection "";
           proxy_pass   http://$stock_backend;
        }
        access_log  /var/log/nginx/server.access.log;
    }
    access_log  /var/log/nginx/access.log;
}
