port 26379

sentinel resolve-hostnames yes
sentinel announce-hostnames yes

sentinel monitor order-db order-db 6379 2
sentinel auth-pass order-db redis
sentinel down-after-milliseconds order-db 3000
sentinel failover-timeout order-db 10000
sentinel parallel-syncs order-db 1

sentinel monitor stock-db stock-db 6379 2
sentinel auth-pass stock-db redis
sentinel down-after-milliseconds stock-db 3000
sentinel failover-timeout stock-db 10000
sentinel parallel-syncs stock-db 1

sentinel monitor payment-db payment-db 6379 2
sentinel auth-pass payment-db redis
sentinel down-after-milliseconds payment-db 3000
sentinel failover-timeout payment-db 10000
sentinel parallel-syncs payment-db 1

sentinel monitor saga-broker saga-broker 6379 2
sentinel auth-pass saga-broker redis
sentinel down-after-milliseconds saga-broker 3000
sentinel failover-timeout saga-broker 10000
sentinel parallel-syncs saga-broker 1