apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  selector:
    app: order-db
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: redis
        image: redis:7.2-bookworm
        command: ["redis-server", "--requirepass", "redis", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: order-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-db-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: stock-db
spec:
  selector:
    app: stock-db
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-db
  template:
    metadata:
      labels:
        app: stock-db
    spec:
      containers:
      - name: redis
        image: redis:7.2-bookworm
        command: ["redis-server", "--requirepass", "redis", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: stock-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-db-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  selector:
    app: payment-db
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: redis
        image: redis:7.2-bookworm
        command: ["redis-server", "--requirepass", "redis", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: payment-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saga-broker-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: saga-broker
spec:
  selector:
    app: saga-broker
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-broker
  template:
    metadata:
      labels:
        app: saga-broker
    spec:
      containers:
      - name: redis
        image: redis:7.2-bookworm
        command: ["redis-server", "--requirepass", "redis", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: saga-broker-pvc
