apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  type: ClusterIP
  selector:
    component: stock
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      component: stock
  template:
    metadata:
      labels:
        component: stock
    spec:
      containers:
        - name: stock
          image: stock:latest
          imagePullPolicy: IfNotPresent
          command: ["gunicorn"]
          args: ["-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:5000", "-w", "4", "--timeout", "30", "app:app"]
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: GATEWAY_URL
              value: "http://gateway:8000"
            - name: REDIS_HOST
              value: "stock-db"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_SENTINEL_HOSTS
              value: "sentinel:26379"
            - name: REDIS_MASTER_NAME
              value: "stock-db"
            - name: SAGA_MQ_REDIS_HOST
              value: "saga-broker"
            - name: SAGA_MQ_REDIS_PORT
              value: "6379"
            - name: SAGA_MQ_REDIS_PASSWORD
              value: "redis"
            - name: SAGA_MQ_SENTINEL_HOSTS
              value: "sentinel:26379"
            - name: SAGA_MQ_MASTER_NAME
              value: "saga-broker"
